### ISSUE TITLE
Create working website for project

### ISSUE THREAD

**Issue by yangrchen** [yangrchen/comp523-cafe-reservation#2]
We need to have a website to support our future project application for our clients. We tentatively decided on using WordPress to host and develop the site for quick updates to the site.

**Comment by pwnham** [comment]
https://docs.google.com/document/d/1EEfflGzs3gQdZIBaRdPlTmhAdSRfj6T6j8hqmRU2zDg/edit?usp=sharing

**Comment by yangrchen** [comment]
Created and submitted Tarheel Live site at https://tarheels.live/carolinacafereserve/
